name: Video Downloader

on:
  push:
    branches:
      - main
    paths:
      - 'download_list.txt'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run downloader
      run: |
        mkdir -p downloads
        python main.py

    - uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        r2-access-key-id: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
        r2-secret-access-key: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
        r2-bucket: hub
        source-dir: ./
        destination-dir: downloads/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()  # 即使失败也上传
      with:
        name: downloaded-videos
        path: downloads/
        retention-days: 1
