name: Video Downloader

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
    paths:
      - 'download_list.txt'  # 只有 download_list.txt 文件变动时才运行（可选）

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run download script
      run: python main.py  # 直接执行根目录下的 main.py
      working-directory: ./  # 明确指定工作目录（可选，默认已是根目录）

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()  # 即使失败也上传
      with:
        name: downloaded-videos
        path: downloads/
        retention-days: 1
