name: Video Downloader

on:
  push:
    branches:
      - main
    paths:
      - 'download_list.txt'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run downloader
      run: |
        mkdir -p downloads
        python main.py

    - name: Upload to Cloudflare R2
      uses: cloudflare/r2-credential-upload@v1
      with:
        account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        bucket-name: your-bucket-name
        key: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
        secret: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
        path: downloads/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()  # 即使失败也上传
      with:
        name: downloaded-videos
        path: downloads/
        retention-days: 1
